apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-deployment
  labels:
    tier: {{ .Values.appName }}-db
    service: {{ .Values.appName }}-service
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      tier: {{ .Values.appName }}-db
      service: {{ .Values.appName }}-service
  template:
    metadata:
      name: {{ .Values.appName }}-name
      labels:
        tier: {{ .Values.appName }}-db
        service: {{ .Values.appName }}-service
    spec:
      containers:
        - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          name: {{ .Values.appName }}
          volumeMounts:
            - mountPath: /data/db
              name: {{ .Values.appName }}
      volumes:
        - name: {{ .Values.appName }}
          persistentVolumeClaim:
            claimName: {{ .Values.appName }}
